### PR TITLE
Hotfix/3.3.16

### PR DESCRIPTION
**Pull request by baumannsven**
This pull provide for use the multi column wizard in his self.

### CODE REVIEW

**Comment by janmarkuslanger** [comment]
Hello there!
I tested the Hotfix. After installation i could not configure any attribute.

Here is the log:
[error.log](https://github.com/menatwork/MultiColumnWizard/files/1747098/error.log)

**Comment by baumannsven** [comment]
@janmarkuslanger You must use for dc-general this branch.
https://github.com/contao-community-alliance/dc-general/tree/hotfix/beta-42

**Comment by baumannsven** [comment]
@janmarkuslanger Did you try again?

**Comment by janmarkuslanger** [comment]
Sorry @baumannsven 

Now it works! :)

**Comment by baumannsven** [comment]
thanks for merge

**Pull request merged**
