### PR TITLE
Fixed dependency to dc-general

### PR DESCRIPTION
**Pull request by bytehead**
see https://github.com/menatwork/MultiColumnWizard/commit/747bdc7d4473079d4f889a39ff5166f1b4c87ee2#commitcomment-24806245

`Fatal error: Uncaught exception Error with message Class 'ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent' not found thrown in system/modules/multicolumnwizard/config/event_listeners.php on line 17`

### CODE REVIEW

**Comment by bytehead** [comment]
:tada: thanks!

**Comment by zonky2** [comment]
@bytehead It´s possible to run a double check?

**Comment by bytehead** [comment]
@zonky2 what do you mean with a double check?

**Comment by zonky2** [comment]
I mean:
* update your package with Contao package manager
* and test it... all o.k.?

**Comment by bytehead** [comment]
It's a dependency of `terminal42/contao-changelanguage`, needs a new tag first. but seems to work if I require `menatwork/contao-multicolumnwizard: dev-master` directly.

**Pull request merged**
