### PR TITLE
Add manipulated data to validator

### PR DESCRIPTION
**Pull request by davidenke**
Appended data by addDataToFieldAtIndex is now recognized by the validator.

### CODE REVIEW

**Comment by davidmaack** [comment]
What exactly are you trying to do here?

**Comment by zonky2** [comment]
ich kann mir darauf keinen Reim machen, was der PR bezwecken soll.. @davidenke bitte Beschreibung nachliefern!

**Comment by davidenke** [comment]
Sorry guys, this PR is 2.5 years old. I can't remember and I'd have to figure it out for myself, too.
But to be honest, I can't see a reason why I should distribute to a project any more which is maintained in every quarter of a decade.

**Comment by zonky2** [comment]
@davidenke thx for your rückmeldung ;-)

**Comment by davidenke** [comment]
@zonky2 Gern geschehen :)

**Pull request closed without merging**
